---
- name: Configuration de base des serveurs
  hosts: all
  become: yes  # Ça veut dire "sudo" automatique
  
  tasks:
    - name: Mettre à jour le cache APT (comme un apt update)
      apt:
        update_cache: yes

    - name: Installer les outils indispensables (Git, Curl, Vim, Htop)
      apt:
        name:
          - git
          - curl
          - vim
          - htop
        state: present
